// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aprpgnczooczvqiolmen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwcnBnbmN6b29jenZxaW9sbWVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4ODk2NjIsImV4cCI6MjA3NDQ2NTY2Mn0.aEAfaBPJaINQUavjw6UFSibPXJb2ZayAQz7wrhPGhHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});